"""add users table, summary/category columns, FK on user_id

Revision ID: f5bbc24d3d61
Revises: 1ef64c8dcab3
Create Date: 2026-08-02 08:56:12.689266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5bbc24d3d61'
down_revision: Union[str, Sequence[str], None] = '1ef64c8dcab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('emails', sa.Column('summary', sa.String(), nullable=True))
    op.add_column('emails', sa.Column('category', sa.String(), nullable=True))
    # Existing rows have user_id=1 with no matching users row yet — this is
    # dev data, fully re-creatable from Gmail via idempotent re-fetch, so we
    # wipe it rather than backfill a placeholder user.
    op.execute("TRUNCATE TABLE emails RESTART IDENTITY")
    op.create_foreign_key(None, 'emails', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'emails', type_='foreignkey')
    op.drop_column('emails', 'category')
    op.drop_column('emails', 'summary')
    op.drop_table('users')
    # ### end Alembic commands ###
